jobs:
  include:
    - stage: test
      language: java
      dist: trusty
      jdk: oraclejdk8
      env:
        - VERSION=4.8.1
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - wget https://services.gradle.org/distributions/gradle-$VERSION-bin.zip
        - unzip -qq gradle-$VERSION-bin.zip
        - export GRADLE_HOME=$PWD/gradle-$VERSION
        - export PATH=$GRADLE_HOME/bin:$PATH
      install:
        - gradle wrapper --gradle-version 5.6.4
        - ./gradlew assemble
      script:
        - ./gradlew test --info

    - stage: test
      language: java
      dist: trusty
      jdk: oraclejdk8
      env:
        - VERSION=5.6.4
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - wget https://services.gradle.org/distributions/gradle-$VERSION-bin.zip
        - unzip -qq gradle-$VERSION-bin.zip
        - export GRADLE_HOME=$PWD/gradle-$VERSION
        - export PATH=$GRADLE_HOME/bin:$PATH
      install:
        - gradle --version
        - gradle assemble
      script:
        - gradle test --info
stages:
  - test
branches:
  only:
    - /.*/
notifications:
  email: false
